/**
 * Registre central des icônes du projet (ng-icons).
 * Seules les icônes listées ici sont incluses dans le bundle (tree-shaking).
 * Pour ajouter une icône : importer son nom puis l'ajouter à `appIcons`.
 *   - UI / pictos  → @ng-icons/lucide       (préfixe « lucide… »)
 *   - logos marque → @ng-icons/simple-icons (préfixe « simple… »)
 * Catalogue : https://lucide.dev/icons · https://simpleicons.org
 */
import {
  lucideArrowRight,
  lucideArrowLeft,
  lucideArrowUpRight,
  lucideChevronRight,
  lucideMail,
  lucideMapPin,
  lucideGlobe,
  lucideUsers,
  lucideUserRound,
  lucideHandshake,
  lucideBriefcase,
  lucideMapPinned,
  lucideLandmark,
  lucideShieldCheck,
  lucideVote,
  lucideSprout,
  lucideCheck,
  lucideSend,
  lucidePlus,
  lucidePencil,
  lucideTrash2,
  lucideLogOut,
  lucideLock,
  lucideHeart,
  lucideCircleUser,
  lucideMessageSquare,
  lucideMenu,
  lucideX,
} from '@ng-icons/lucide';
import {
  simpleFacebook,
  simpleX,
  simpleInstagram,
  simpleThreads,
  simpleYoutube,
  simpleWhatsapp,
} from '@ng-icons/simple-icons';

export const appIcons = {
  lucideArrowRight,
  lucideArrowLeft,
  lucideArrowUpRight,
  lucideChevronRight,
  lucideMail,
  lucideMapPin,
  lucideGlobe,
  lucideUsers,
  lucideUserRound,
  lucideHandshake,
  lucideBriefcase,
  lucideMapPinned,
  lucideLandmark,
  lucideShieldCheck,
  lucideVote,
  lucideSprout,
  lucideCheck,
  lucideSend,
  lucidePlus,
  lucidePencil,
  lucideTrash2,
  lucideLogOut,
  lucideLock,
  lucideHeart,
  lucideCircleUser,
  lucideMessageSquare,
  lucideMenu,
  lucideX,
  simpleFacebook,
  simpleX,
  simpleInstagram,
  simpleThreads,
  simpleYoutube,
  simpleWhatsapp,
};
